version: "3"

services:
  tesla-monitor:
    image: turboyangcn/tesla-monitor:latest
    container_name: 'Tesla-Monitor'
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - Language=zh-CN
    depends_on:
      - database
    ports:
      - 6000:80
    volumes:
      - ./Logs:/app/Logs
    networks:
      - network

  database:
    image: postgis/postgis:latest
    container_name: 'Tesla-Monitor-Database'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TeslaMonitor
      - TZ=Asia/Shanghai
    ports:
      - 54322:5432
    volumes:
      - ./Database:/var/lib/postgresql/data
    networks:
      - network

  grafana:
    image: turboyangcn/tesla-monitor-grafana:latest
    container_name: 'Tesla-Monitor-Grafana'
    restart: always
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_NAME=TeslaMonitor
      - TZ=Asia/Shanghai
    ports:
      - 7000:3000
    volumes:
      - ./Grafana:/var/lib/grafana
    networks:
      - network

networks:
  network:
   name: 'Tesla Monitor Network'