apiVersion: 1

datasources:
- name: TeslaMonitor
  type: postgres
  url: $DATABASE_HOST:$DATABASE_PORT
  user: $DATABASE_USER
  database: $DATABASE_NAME
  password: ""
  access: proxy
  basicAuth: false
  withCredentials: false
  isDefault: true
  secureJsonData:
    password: $DATABASE_PASS
  jsonData:
    postgresVersion: 1300
    sslmode: disable
  version: 1
  editable: false