{
 "title": "Overview",
 "description": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Car",
    "label": "Car",
    "query": "SELECT \"Name\" AS __text, \"Id\" AS __value FROM \"Car\";"
   },
   {
    "name": "LengthUnit",
    "label": "Length Unit",
    "query": "Kilometer : Kilometer, Mile : Mile"
   },
   {
    "name": "TemperatureUnit",
    "label": "Temperature Unit",
    "query": "Celsius : Celsius, Fahrenheit : Fahrenheit"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"State\"\nFROM \"State\"\nWHERE\n  \"State\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"CreateTimestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Fireware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Version\"\nFROM \"Fireware\"\nWHERE\n  \"Version\" IS NOT NULL AND \"State\" = 'Updated' AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  (CASE\n    WHEN '$LengthUnit' = 'Kilometer' THEN \"Odometer\" * 25146 / 15625\n    ELSE\n      \"Odometer\"\n    END) AS \"Odometer_$LengthUnit\"\nFROM \"Snapshot\"\nWHERE\n  \"Odometer\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  (CASE\n    WHEN '$LengthUnit' = 'Kilometer' THEN \"BatteryRange\" * 25146 / 15625\n    ELSE\n      \"BatteryRange\"\n    END) AS \"BatteryRange_$LengthUnit\"\nFROM \"Snapshot\"\nWHERE\n  \"BatteryRange\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  5::float as \"metric\",\n  st_y(\"Location\"::geometry) as \"latitude\",\n  st_x(\"Location\"::geometry) as \"longitude\"\nFROM \"Snapshot\"\nWHERE\n  \"Location\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  \"BatteryLevel\"\nFROM \"Snapshot\"\nWHERE\n  \"BatteryLevel\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Charging Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "V" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  \"ChargerVoltage\"\nFROM \"Snapshot\"\nWHERE\n  \"ChargerVoltage\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Charging Current",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  \"ChargerActualCurrent\"\nFROM \"Snapshot\"\nWHERE\n  \"ChargerActualCurrent\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Charging Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  \"ChargerPower\"\nFROM \"Snapshot\"\nWHERE\n  \"ChargerPower\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Outside Temp.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  (CASE\n    WHEN '$TemperatureUnit' = 'Fahrenheit' THEN round(\"OutsideTemperature\" * 9 / 5 + 32, 1)\n    ELSE\n      \"OutsideTemperature\"\n    END) AS \"OutsideTemperature_$TemperatureUnit\"\nFROM \"Snapshot\"\nWHERE\n  \"OutsideTemperature\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Inside Temp.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  (CASE\n    WHEN '$TemperatureUnit' = 'Fahrenheit' THEN round(\"InsideTemperature\" * 9 / 5 + 32, 1)\n    ELSE\n      \"InsideTemperature\"\n    END) AS \"InsideTemperature_$TemperatureUnit\"\nFROM \"Snapshot\"\nWHERE\n  \"InsideTemperature\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Driver Temp.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  (CASE\n    WHEN '$TemperatureUnit' = 'Fahrenheit' THEN round(\"DriverTemperatureSetting\" * 9 / 5 + 32, 1)\n    ELSE\n      \"DriverTemperatureSetting\"\n    END) AS \"DriverTemperatureSetting_$TemperatureUnit\"\nFROM \"Snapshot\"\nWHERE\n  \"DriverTemperatureSetting\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Passenger Temp.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  (CASE\n    WHEN '$TemperatureUnit' = 'Fahrenheit' THEN round(\"PassengerTemperatureSetting\" * 9 / 5 + 32, 1)\n    ELSE\n      \"PassengerTemperatureSetting\"\n    END) AS \"PassengerTemperatureSetting_$TemperatureUnit\"\nFROM \"Snapshot\"\nWHERE\n  \"PassengerTemperatureSetting\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  (CASE\n    WHEN '$LengthUnit' = 'Kilometer' AND \"ShiftState\" = 'R' THEN -\"Speed\" * 25146 / 15625\n    WHEN '$LengthUnit' = 'Kilometer' AND \"ShiftState\" <> 'R' THEN \"Speed\" * 25146 / 15625\n    WHEN '$LengthUnit' = 'Mile' AND \"ShiftState\" = 'R' THEN -\"Speed\"\n    WHEN '$LengthUnit' = 'Mile' AND \"ShiftState\" <> 'R' THEN \"Speed\"\n    END) AS \"Speed_$LengthUnit\"\nFROM \"Snapshot\"\nWHERE\n  \"Speed\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Elevation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  (CASE\n    WHEN '$LengthUnit' = 'Kilometer' THEN \"Elevation\"\n    WHEN '$LengthUnit' = 'Mile' THEN \"Elevation\" * 3.2808399\n    END) AS \"Elevation_$LengthUnit\"\nFROM \"Snapshot\"\nWHERE\n  \"Elevation\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Shift",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN \"ShiftState\" = 'N' THEN 1\n    WHEN \"ShiftState\" = 'D' THEN 2\n    WHEN \"ShiftState\" = 'R' THEN 3\n    ELSE\n      0\n  END\nFROM \"Snapshot\"\nWHERE\n  \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Using Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  \"Power\"\nFROM \"Snapshot\"\nWHERE\n  \"Power\" IS NOT NULL AND \"CarId\" = $Car\nORDER BY \"Timestamp\" DESC\nLIMIT 1"
    }
   ]
  }
 ]
}